### About
This notebook contains simple, toy examples to help you get started with FairMLHealth tool usage. This same content is mirrored in the repository's main [README](../../../README.md)

### Example Setup

In [9]:
from fairmlhealth import model_comparison as fhmc, reports

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, TweedieRegressor
np.random.seed(547)

# Load data
X = pd.DataFrame({'A': np.random.randint(1, 4, 8),
                  'B': np.random.randint(1, 8, 8),
                  'C': np.random.randint(1, 16, 8),
                  'D': np.random.uniform(-10, 10, 8),
                  'gender': [0, 0, 0, 0, 1, 1, 1, 1],
                  'ethnicity': [0, 1, 0, 1, 0, 1, 0, 1]
                  })
targ_data = np.random.uniform(-10, 10, 8)
y = pd.Series(targ_data, index=X.index, name="y")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.75, random_state=36)

#Train models
model_1 = LinearRegression().fit(X_train, y_train)
model_2 = TweedieRegressor().fit(X_train, y_train)

# Deterimine your set of protected attributes
prtc_attr = X_test['gender']

# Specify either a dict or a list of trained models to compare
model_dict = {'model_1': model_1, 'model_2': model_2}

In [10]:
display(X)

   A  B   C         D  gender  ethnicity
0  3  6   6 -7.238693       0          0
1  2  4   3 -0.984641       0          1
2  2  5   4  1.586278       0          0
3  3  2   2  5.386886       0          1
4  1  4  13  2.073338       1          0
5  3  4   1  8.739900       1          1
6  3  5  11  3.116568       1          0
7  2  7   1  6.048523       1          1

### Model Measurement
The primary feature of this library is the model comparison tool. The current version supports assessment of binary prediction models through use of the measure_models and compare_models functions.

Measure_model is designed to generate a report of multiple fairness metrics for a single model. Here it is shown wrapped in a "flag" function to emphasize values that are outside of the "fair" range.

In [11]:
# Generate a pandas dataframe of measures
fhmc.measure_model(X_test, y_test, prtc_attr, model_1, pred_type="regression")

                                                                       Value
Group Fairness                   Mean Prediction Ratio               -2.0927
                                 scMAE Ratio                          0.0795
                                 MAE Ratio                            0.0723
                                 Mean Error Ratio                     2.1531
                                 Mean Prediction Difference          -2.1647
                                 scMAE Difference                    -0.4649
                                 MAE Difference                      -6.4441
                                 Mean Error Difference               -0.1707
Individual Fairness              Consistency Score                   -2.0265
                                 Between-Group Gen. Entropy Error     0.0000
Model Performance (Weighted Avg) Target Mean                         -0.1490
                                 Pred. Mean                          -0.3824
                                 scMAE                                0.2238
                                 MSE                                 32.4974
                                 MAE                                  3.7240
                                 Rsqrd                               -0.0477
Data Metrics                     Prevalence of Privileged Class (%)   0.0000

### Evaluating

FairMLHealth now also includes stratified reporting features to aid in identifying the source of unfairness or other bias: data reports, performance reports, and bias reports. Note that these stratified reports can evaluate multiple features at once, and that there are two options for identifying which features to assess.

Note that the flag tool has not yet been updated to work with stratified reports.

#### Stratified Data Reports

The data reporter is shown below with each of the two data argument options. It evaluates basic statistics specific to each feature-value, in addition to relative statistics for the target value. Since the reporter can evaluate many features at once, it can be a useful option for identifying patterns of bias either alone or in concert with other (e.g., visual methods).

In [12]:
# Arguments Option 1: pass full set of data, subsetting with *features* argument
reports.data_report(X_test, y_test, features=['gender'])

,Feature Name,Feature Value,Obs.,Missing Values,Feature Entropy,Target Max,Target Mean,Target Median,Target Min,Target Std. Dev.,Value Prevalence
0,ALL FEATURES,ALL VALUES,6.0,0,NaN,8.7043,-0.149,-0.5909,-7.9329,6.1010,1.0
1,gender,0,3.0,0,1.0,4.5639,-1.146,-0.0690,-7.9329,6.3177,0.5
2,gender,1,3.0,0,1.0,8.7043,0.848,-1.1128,-5.0475,7.0825,0.5

#### Stratified Performance Reports

The stratified perofrmance reporter evaluates model performance specific to each feature-value subset. If prediction probabilities are available to the model, additional ROC AUC and PR AUC values will be included.

In [13]:
reports.performance_report(X_test[['gender']], y_test, model_1.predict(X_test), pred_type="regression")

,Feature Name,Feature Value,Obs.,Target Mean,Pred. Mean,Error Mean,Error Std. Dev.,MAE,MSE,Pred. Median,Pred. Std. Dev.,scMAE
0,ALL FEATURES,ALL VALUES,6.0,-0.149,-0.3824,-0.2334,6.2395,3.7240,32.4974,-0.9831,4.8877,0.2238
1,gender,0,3.0,-1.146,-1.4647,-0.3188,0.7997,0.5020,0.5280,-1.3001,6.3736,0.0402
2,gender,1,3.0,0.848,0.6999,-0.1480,9.8319,6.9461,64.4667,-0.6661,3.9480,0.5051

In [14]:
reports.performance_report(X_test[['gender']], y_test, model_1.predict(X_test), pred_type="regression")

,Feature Name,Feature Value,Obs.,Target Mean,Pred. Mean,Error Mean,Error Std. Dev.,MAE,MSE,Pred. Median,Pred. Std. Dev.,scMAE
0,ALL FEATURES,ALL VALUES,6.0,-0.149,-0.3824,-0.2334,6.2395,3.7240,32.4974,-0.9831,4.8877,0.2238
1,gender,0,3.0,-1.146,-1.4647,-0.3188,0.7997,0.5020,0.5280,-1.3001,6.3736,0.0402
2,gender,1,3.0,0.848,0.6999,-0.1480,9.8319,6.9461,64.4667,-0.6661,3.9480,0.5051

#### Stratified Bias Fairness Reports

The stratified bias reporter presents model bias specific to each feature-value subset. Inspired by common measures of fairness, the reporter assumes each feature-value as the "privileged" group relative to all other possible values for the feature. For example, row 3 in the table below displaying measures of "col1" value of "2" where 2 is considered to be the privileged group and all other values (1, 2, 45, and 50) are considered unprivileged.

To simplify the report, fairness measures have been simplified to their component parts. For example, measures of Equalized Odds can be determined by combining the True Positive Rate (TPR) Ratios & Differences with False Positive Rate (FPR) Ratios & Differences.

See also: [Fairness Quick References](../docs/Fairness_Quick_References.pdf) and the [Tutorial for Evaluating Fairness in Binary Classification](./Tutorial-EvaluatingFairnessInBinaryClassification.ipynb)

In [17]:
reports.bias_report(X_test[['gender', 'B']], y_test, model_1.predict(X_test), 
                    pred_type="regression")

,Feature Name,Feature Value,Obs.,MAE Difference,MAE Ratio,Mean Error Difference,Mean Error Ratio,Mean Prediction Difference,Mean Prediction Ratio,scMAE Difference,scMAE Ratio
0,gender,0,3,6.4441,13.8371,0.1707,0.4645,2.1647,-0.4779,0.4649,12.5744
1,gender,1,3,-6.4441,0.0723,-0.1707,2.1531,-2.1647,-2.0927,-0.4649,0.0795
2,B,2,1,4.1556,16.9196,-0.5933,-1.2730,-6.2489,-0.2951,0.0044,1.0170
3,B,4,2,3.7096,3.9655,1.5263,-0.2201,2.1892,-0.1886,-0.9002,0.2488
4,B,5,1,-6.7757,0.2769,10.9644,-0.1701,0.3405,0.4889,-9.1628,0.0222
5,B,6,1,4.4523,323.2620,-0.2967,-20.4726,9.0440,-0.1421,0.3109,23.5068
6,B,7,1,-7.7676,0.2382,-12.5166,-0.2275,-6.6383,-0.2891,-10.0511,0.0143

### Comparing Results for Multiple Models

The compare_models feature can be used to generate side-by-side fairness comparisons of multiple models. Model performance metrics such as accuracy and precision are also provided to facilitate comparison.   

Below is an example output comparing the two example models defined above. Missing values have been added for metrics requiring prediction probabilities, which the second model does not have (note the warning below).

The compare_models function can also be used to measure two different protected attributes. Protected attributes are measured separately and cannot yet be combined together with this tool.

In [18]:
fhmc.compare_models(X_test, y_test, 
                     [X_test['gender'], X_test['ethnicity']], 
                      {'gender':model_1, 'ethnicity':model_1},
                      pred_type="regression")

                                                                      gender  \
Group Fairness                   Mean Prediction Ratio               -2.0927
                                 scMAE Ratio                          0.0795
                                 MAE Ratio                            0.0723
                                 Mean Error Ratio                     2.1531
                                 Mean Prediction Difference          -2.1647
                                 scMAE Difference                    -0.4649
                                 MAE Difference                      -6.4441
                                 Mean Error Difference               -0.1707
Individual Fairness              Consistency Score                   -2.0265
                                 Between-Group Gen. Entropy Error     0.0000
Model Performance (Weighted Avg) Target Mean                         -0.1490
                                 Pred. Mean                          -0.3824
                                 scMAE                                0.2238
                                 MSE                                 32.4974
                                 MAE                                  3.7240
                                 Rsqrd                               -0.0477
Data Metrics                     Prevalence of Privileged Class (%)   0.0000

                                                                     ethnicity
Group Fairness                   Mean Prediction Ratio                 -1.2645
                                 scMAE Ratio                            0.5266
                                 MAE Ratio                              0.9115
                                 Mean Error Ratio                      -1.1518
                                 Mean Prediction Difference            -6.5478
                                 scMAE Difference                      -0.1919
                                 MAE Difference                        -0.3447
                                 Mean Error Difference                 -6.6181
Individual Fairness              Consistency Score                     -2.0265
                                 Between-Group Gen. Entropy Error       0.0000
Model Performance (Weighted Avg) Target Mean                           -0.1490
                                 Pred. Mean                            -0.3824
                                 scMAE                                  0.2238
                                 MSE                                   32.4974
                                 MAE                                    3.7240
                                 Rsqrd                                 -0.0477
Data Metrics                     Prevalence of Privileged Class (%)     0.0000